// T1.1 测试用例表（非测试文件）：Semantic IR 各对象的合法/非法样例表。
// 由 tests/m1/ir-schemas.test.ts 消费；fixtures 来自 ./ir-samples.ts。
// 对象编号固定（S1-S4/C1-C11/P1-P5/M1-M8/A1-A4，架构 §4.2/§4.3 全量）。
import {
  ActionContractSchema,
  ActionSchema,
  ActivationContractSchema,
  ArtifactSchema,
  BeliefSchema,
  CapabilitySchema,
  CheckpointSchema,
  ClaimSchema,
  ContextProjectionSchema,
  ContradictionSchema,
  DecisionSchema,
  EventSchema,
  EvidenceSchema,
  EvolutionObjectSchema,
  ExperienceSchema,
  HypothesisSchema,
  IntentSchema,
  MaintenanceDebtSchema,
  MemorySchema,
  ObservationSchema,
  OpenQuestionSchema,
  OperatorSchema,
  ProcessSchema,
  ProvenanceSchema,
  RuntimeSnapshotSchema,
  S4Schema,
  SkillSchema,
  SkillStackSchema,
  StateSchema,
  TaskContractSchema,
  WorkingStateSchema,
} from '../../kernel/schemas/index.js';
import {
  A1_VALID,
  A2_VALID,
  A3_VALID,
  AC_VALID,
  C1_VALID,
  C2_VALID,
  C3_VALID,
  C4_VALID,
  C5_VALID,
  C6_VALID,
  C7_VALID,
  C8_VALID,
  C10_VALID,
  C11_VALID,
  M1_VALID,
  M3_VALID,
  M4_VALID,
  M5_VALID,
  M6_VALID,
  M7_VALID,
  M8_VALID,
  OP_VALID,
  P1_VALID,
  P3_VALID,
  P4_VALID,
  P5_VALID,
  PROV,
  S1_VALID,
  S2_VALID,
  S3_VALID,
  SM_VALID,
  WM_VALID,
  omit,
  type ZodLike,
} from './ir-samples.js';

/** 合法样例表：[名称, schema, 样例] —— 全量编号（28 核心 + 4 一等，S4 双变体） */
export const VALID: Array<[string, ZodLike, unknown]> = [
  ['S1 TaskContract', TaskContractSchema, S1_VALID],
  ['S2 State', StateSchema, S2_VALID],
  ['S3 WorkingState', WorkingStateSchema, S3_VALID],
  ['S4 WorldModel', S4Schema, WM_VALID],
  ['S4 SelfModel', S4Schema, SM_VALID],
  ['C1 Claim', ClaimSchema, C1_VALID],
  ['C2 Hypothesis', HypothesisSchema, C2_VALID],
  ['C3 Contradiction', ContradictionSchema, C3_VALID],
  ['C4 Evidence', EvidenceSchema, C4_VALID],
  ['C5 Observation', ObservationSchema, C5_VALID],
  ['C6 Belief', BeliefSchema, C6_VALID],
  ['C7 OpenQuestion', OpenQuestionSchema, C7_VALID],
  ['C8 Action', ActionSchema, C8_VALID],
  ['C9 ActionContract', ActionContractSchema, AC_VALID],
  ['C10 Decision', DecisionSchema, C10_VALID],
  ['C11 Experience', ExperienceSchema, C11_VALID],
  ['P1 Process', ProcessSchema, P1_VALID],
  ['P2 Operator', OperatorSchema, OP_VALID],
  ['P3 Capability', CapabilitySchema, P3_VALID],
  ['P4 Intent', IntentSchema, P4_VALID],
  ['P5 Skill', SkillSchema, P5_VALID],
  ['M1 Memory', MemorySchema, M1_VALID],
  ['M2 Provenance', ProvenanceSchema, PROV],
  ['M3 Event', EventSchema, M3_VALID],
  ['M4 EvolutionObject', EvolutionObjectSchema, M4_VALID],
  ['M5 RuntimeSnapshot', RuntimeSnapshotSchema, M5_VALID],
  ['M6 ActivationContract', ActivationContractSchema, M6_VALID],
  ['M7 Checkpoint', CheckpointSchema, M7_VALID],
  ['M8 MaintenanceDebt', MaintenanceDebtSchema, M8_VALID],
  ['A1 Artifact', ArtifactSchema, A1_VALID],
  ['A2 SkillStack', SkillStackSchema, A2_VALID],
  ['A3 ContextProjection', ContextProjectionSchema, A3_VALID],
];

/** 非法样例表：缺必填 / 类型错 / 枚举非法值（每对象 ≥1；A4 为接口无运行时校验） */
export const INVALID: Array<[string, ZodLike, unknown]> = [
  ['S1 缺 goal', TaskContractSchema, omit(S1_VALID, 'goal')],
  ['S1 budget 类型错', TaskContractSchema, { ...S1_VALID, budget: 'lots' }],
  ['S2 缺 working', StateSchema, omit(S2_VALID, 'working')],
  ['S3 缺 goal', WorkingStateSchema, omit(S3_VALID, 'goal')],
  ['S3 next_best_action 类型错', WorkingStateSchema, { ...S3_VALID, next_best_action: 42 }],
  ['S4 kind 非法值', S4Schema, { ...WM_VALID, kind: 'planet' }],
  ['S4 WorldModel 缺 capabilities', S4Schema, omit(WM_VALID, 'capabilities')],
  ['C1 缺 text', ClaimSchema, omit(C1_VALID, 'text')],
  ['C1 epistemic 非法值', ClaimSchema, { ...C1_VALID, epistemic: 'yes' }],
  ['C1 confidence 越界', ClaimSchema, { ...C1_VALID, confidence: 1.5 }],
  ['C2 status 非法值', HypothesisSchema, { ...C2_VALID, status: 'banned' }],
  ['C3 缺 left_claim', ContradictionSchema, omit(C3_VALID, 'left_claim')],
  ['C3 unresolved 类型错', ContradictionSchema, { ...C3_VALID, unresolved: 'yes' }],
  ['C4 缺 observation_ref', EvidenceSchema, omit(C4_VALID, 'observation_ref')],
  ['C5 from 非法值', ObservationSchema, { ...C5_VALID, from: 'robot' }],
  ['C6 缺 claim_ref', BeliefSchema, omit(C6_VALID, 'claim_ref')],
  ['C6 state.confidence 越界', BeliefSchema, {
    ...C6_VALID,
    state: { historical: [], current: 'c:1', transition_event: 'evt:1', confidence: 2 },
  }],
  ['C7 缺 question', OpenQuestionSchema, omit(C7_VALID, 'question')],
  ['C7 cost 类型错', OpenQuestionSchema, { ...C7_VALID, cost: 'high' }],
  ['C8 缺 contract', ActionSchema, omit(C8_VALID, 'contract')],
  ['C8 state 非法值', ActionSchema, { ...C8_VALID, state: 'paused' }],
  ['C9 缺 preconditions', ActionContractSchema, omit(AC_VALID, 'preconditions')],
  ['C9 reversibility.declared 类型错', ActionContractSchema, {
    ...AC_VALID,
    reversibility: { declared: 'yes', rollback_path: 'rb:1' },
  }],
  ['C10 缺 chosen', DecisionSchema, omit(C10_VALID, 'chosen')],
  ['C10 lineage 类型错', DecisionSchema, { ...C10_VALID, lineage: 'x' }],
  ['C11 缺 action', ExperienceSchema, omit(C11_VALID, 'action')],
  ['C11 relations.requires 类型错', ExperienceSchema, {
    ...C11_VALID,
    relations: { requires: 'x', excludes: [], fallback: [], causes: [], supersedes: [] },
  }],
  ['P1 缺 operator_graph', ProcessSchema, omit(P1_VALID, 'operator_graph')],
  ['P2 error.timeout_ms 类型错', OperatorSchema, {
    ...OP_VALID,
    error: { retryable: true, timeout_ms: 'fast', cancelable: true, rollback: 'rb:1' },
  }],
  ['P3 缺 provider', CapabilitySchema, omit(P3_VALID, 'provider')],
  ['P3 stats.calls 负数', CapabilitySchema, { ...P3_VALID, stats: { calls: -1, failures: 0 } }],
  ['P4 effects 非法值', IntentSchema, { ...P4_VALID, effects: 'write' }],
  ['P5 source 非法值', SkillSchema, { ...P5_VALID, source: 'mystery' }],
  ['M1 缺 kind', MemorySchema, omit(M1_VALID, 'kind')],
  ['M1 lifecycle 非法值', MemorySchema, { ...M1_VALID, lifecycle: 'Warm' }],
  ['M2 缺 source', ProvenanceSchema, omit(PROV, 'source')],
  ['M2 environment 缺 os', ProvenanceSchema, {
    ...PROV,
    environment: { node: '24.12.0', dsh_version: '0.1.0', project: 'omb-v2' },
  }],
  ['M3 缺 session_id', EventSchema, omit(M3_VALID, 'session_id')],
  ['M3 type 非法值', EventSchema, { ...M3_VALID, type: 'session/foo' }],
  ['M3 通配段残缺', EventSchema, { ...M3_VALID, type: 'process/operator/' }],
  ['M4 缺 spdx', EvolutionObjectSchema, omit(M4_VALID, 'spdx')],
  ['M4 parent 类型错', EvolutionObjectSchema, { ...M4_VALID, parent: 3 }],
  ['M5 philosophy 非 sha256', RuntimeSnapshotSchema, {
    ...M5_VALID,
    components: {
      scheduler: 's:1',
      memory: 'm:1',
      verifier: 'v:1',
      renderer: 'r:1',
      capability: 'c:1',
      philosophy: 'xx',
    },
  }],
  ['M6 缺 candidate', ActivationContractSchema, omit(M6_VALID, 'candidate')],
  ['M7 timestamp 类型错', CheckpointSchema, { ...M7_VALID, timestamp: 1 }],
  ['M8 value 负数', MaintenanceDebtSchema, { ...M8_VALID, value: -0.1 }],
  ['A1 缺 content', ArtifactSchema, omit(A1_VALID, 'content')],
  ['A1 hash 非 64hex', ArtifactSchema, { ...A1_VALID, hash: 'xx' }],
  ['A1 可变对象不得 sha256 id', ArtifactSchema, { ...A1_VALID, immutable: false }],
  ['A2 缺 skills', SkillStackSchema, omit(A2_VALID, 'skills')],
  ['A2 validated 类型错', SkillStackSchema, { ...A2_VALID, validated: 'yes' }],
  ['A2 immutable 必须为 true', SkillStackSchema, { ...A2_VALID, immutable: false }],
  ['A3 type 非法值', ContextProjectionSchema, { ...A3_VALID, type: 'scratch' }],
  ['A3 total_tokens 类型错', ContextProjectionSchema, { ...A3_VALID, total_tokens: 'ten' }],
];
